products:
  handler: src/routes/products/v1/index.products
  timeout: 300
  memorySize: 300
  events:
    - http:
        path: /v1/products
        method: any
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          allowCredentials: true
    - http:
        path: /v1/products/{proxy+}
        method: any
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          allowCredentials: true
