name: Deploying backend from main

on:
  push:
    branches:
      - main
env:
  ENVIRONMENT: backend
  STAGE: dev
  DBHOST: ${{ secrets.DB_HOST }}
  DBUSER: ${{ secrets.DB_USER }}
  DBDATABASE: vyapara
  DBPASSWORD: ${{ secrets.DB_PASSWORD }}
  DBPORT: ${{ secrets.DB_PORT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_KEY }}
  DBSCHEMA: vyapara
  #AWS_PROFILE: developer
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET }}
  DEV_OTP: ${{ secrets.DEV_OTP }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  #STAGE: ${{ secrets.STAGE }}
  JWT_PRIVKEY: ${{ secrets.JWT_PRIVKEY }}
  # EMAIL_ENABLED: true
  # JWT_PUBKEY: ${{ secrets.JWT_PUBKEY }}
  MAX_RESUMPTION_DAYS: 30
  API_ENDPOINT: https://example.com/dev/
  # STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  # STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  # SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
  # SQUARE_APP_ID: ${{ secrets.SQUARE_APP_ID }}
  # SQUARE_APP_LOCATION: ${{ secrets.SQUARE_APP_LOCATION }}
  # PAYMENT_GATEWAY: ${{ secrets.PAYMENT_GATEWAY }}
  # FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  PRESCRIPTION_PREFIX: TEST
  MAIN_APP_URL: https://www.vyapara.com
  SES_REGION: ${{ secrets.SES_REGION}}
  # INTERNAL_KEY:  ${{ secrets.INTERNAL_KEY }}
  # EMAIL_HOST:  ${{ secrets.EMAIL_HOST }}
  # EMAIL_PORT:  ${{ secrets.EMAIL_PORT }}
  # EMAIL_SSL:  ${{ secrets.EMAIL_SSL }}
  # EMAIL_USER:  ${{ secrets.EMAIL_USER }}
  # EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
  # TWILIO_ACCOUNT_SID:  ${{ secrets.TWILIO_ACCOUNT_SID }}
  # TWILIO_AUTH_TOKEN:  ${{ secrets.TWILIO_AUTH_TOKEN }}
  # TWILIO_PHONE_NUMBER:  ${{ secrets.TWILIO_PHONE_NUMBER }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install  --force
      - name: Run Linter/Formatter
        run: npm run lint
  deploy:
    name: deploy
    runs-on: ubuntu-22.04
    needs: [lint]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install  --force
      # - name: Set AWS profile
      #  run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile developer && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile developer && aws configure set region "ca-central-1" --profile developer
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET }}
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: npm ls
        run: npm ls
